# Generated by Django 3.2.9 on 2021-11-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0014_delete_manualbooking'),
        ('HOME', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
