# Generated by Django 3.2.9 on 2021-11-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0008_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
