# Generated by Django 3.2.9 on 2021-11-21 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOME', '0009_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessname', models.TextField(blank=True, max_length=50)),
                ('businessaddress', models.TextField(blank=True, max_length=50)),
                ('country', models.TextField(blank=True, max_length=50)),
                ('city', models.TextField(blank=True, max_length=50)),
                ('areapostalcode', models.TextField(blank=True, max_length=50)),
                ('natureofbusiness', models.TextField(blank=True, max_length=50)),
                ('numberofshipmentspermonth', models.TextField(blank=True, max_length=50)),
                ('sellingplatform', models.TextField(blank=True, max_length=50)),
                ('sellingplatformlink', models.TextField(blank=True, max_length=50)),
                ('cnic_ntn', models.TextField(blank=True, max_length=50)),
                ('profile_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
