# Generated by Django 3.2.9 on 2021-11-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0011_auto_20211122_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='information_filled',
            field=models.BooleanField(default=False),
        ),
    ]
