# Generated by Django 3.2.9 on 2021-11-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0005_manualbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manualbooking',
        ),
    ]
