# Generated by Django 3.2.9 on 2021-11-10 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HOME', '0001_initial'),
        ('BOOKINGS', '0006_delete_manualbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='manualbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConsignorName', models.CharField(max_length=100)),
                ('ConsignorAddress', models.CharField(max_length=100)),
                ('ConsigneeName', models.CharField(max_length=100)),
                ('ConsigneeMobileNumber', models.CharField(max_length=13)),
                ('ConsigneeEmail', models.CharField(max_length=50)),
                ('ConsigneeAddress', models.CharField(max_length=50)),
                ('CODAmount', models.IntegerField()),
                ('ProductDetail', models.CharField(max_length=50)),
                ('ORIGINCITY', models.CharField(max_length=50)),
                ('DestinationCity', models.CharField(max_length=50)),
                ('Weight', models.IntegerField()),
                ('Pieces', models.IntegerField()),
                ('ServiceType', models.CharField(max_length=50)),
                ('SpecialHandling', models.CharField(max_length=50)),
                ('Reference', models.CharField(blank=True, max_length=50)),
                ('Remarks', models.CharField(blank=True, max_length=50)),
                ('BookingDate_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('BookingNumber', models.CharField(default=uuid.uuid4, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.users')),
            ],
        ),
    ]
