# Generated by Django 3.2.9 on 2021-11-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0007_manualbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manualbooking',
        ),
    ]
