# Generated by Django 3.2.9 on 2021-11-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0015_manualbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manualbooking',
        ),
    ]
