# Generated by Django 3.2.9 on 2021-11-16 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0017_manualbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbooking',
            name='DeliveredStatus_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='Delivered_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='PickedStatus_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='Picked_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='ReturnedStatus_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='Returned_Status',
            field=models.BooleanField(default=False),
        ),
    ]
