# Generated by Django 3.2.9 on 2021-11-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0018_auto_20211116_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbooking',
            name='DeliveredStatus_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
