# Generated by Django 3.2.9 on 2021-11-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0019_alter_manualbooking_deliveredstatus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbooking',
            name='PickedStatus_date',
            field=models.DateTimeField(blank=True, default='NOT SET'),
        ),
    ]
