# Generated by Django 3.2.9 on 2021-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0021_alter_manualbooking_pickedstatus_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualbooking',
            old_name='Reference',
            new_name='Order_id',
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='ConsigneeEmail',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
