# Generated by Django 3.2.9 on 2021-12-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0024_auto_20211128_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualbooking',
            old_name='AddressLabel_Generated',
            new_name='AddressLabel_Printed',
        ),
    ]
