# Generated by Django 3.2.9 on 2022-01-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0025_rename_addresslabel_generated_manualbooking_addresslabel_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbooking',
            name='AddressLabel_Printed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='Loadsheet_Generated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
