# Generated by Django 3.2.9 on 2022-01-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0026_auto_20220118_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbooking',
            name='Booking_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='assigned_to_loadsheet_number',
            field=models.IntegerField(null=True),
        ),
    ]
