# Generated by Django 3.2.9 on 2022-01-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKINGS', '0027_auto_20220118_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbooking',
            name='delivery_assigned_to_rider',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='pickup_assigned_to_rider',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
